In [1]:
import pandas as pd

In [2]:
geoloc = pd.read_csv(r"C:\Users\Administrator\Documents\1st Project\Raw_data\olist_geolocation_dataset.csv")

In [3]:
geoloc.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [4]:
geoloc.shape

(1000163, 5)

In [5]:
geoloc.dtypes

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

In [6]:
geoloc.info

<bound method DataFrame.info of          geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                               1037       -23.545621       -46.639292
1                               1046       -23.546081       -46.644820
2                               1046       -23.546129       -46.642951
3                               1041       -23.544392       -46.639499
4                               1035       -23.541578       -46.641607
...                              ...              ...              ...
1000158                        99950       -28.068639       -52.010705
1000159                        99900       -27.877125       -52.224882
1000160                        99950       -28.071855       -52.014716
1000161                        99980       -28.388932       -51.846871
1000162                        99950       -28.070104       -52.018658

        geolocation_city geolocation_state
0              sao paulo                SP
1              sao paulo                SP
2              sao paulo                SP
3              sao paulo                SP
4              sao paulo                SP
...                  ...               ...
1000158         tapejara                RS
1000159   getulio vargas                RS
1000160         tapejara                RS
1000161  david canabarro                RS
1000162         tapejara                RS

[1000163 rows x 5 columns]>

In [7]:
geoloc.isnull()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
...,...,...,...,...,...
1000158,False,False,False,False,False
1000159,False,False,False,False,False
1000160,False,False,False,False,False
1000161,False,False,False,False,False
1000162,False,False,False,False,False

In [8]:
geoloc.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

In [9]:
geoloc.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
1000158    False
1000159     True
1000160     True
1000161    False
1000162     True
Length: 1000163, dtype: bool

In [10]:
geoloc.duplicated().sum()

np.int64(261831)

In [11]:
geoloc["geolocation_city"].nunique()

8011

In [12]:
geoloc["geolocation_city"] = geoloc["geolocation_city"].str.lower().str.strip()

In [13]:
geoloc["geolocation_city"].nunique()

8010

In [14]:
geoloc["geolocation_state"].nunique()

27

In [15]:
geoloc["geolocation_state"] = geoloc["geolocation_state"].str.upper().str.strip()

In [16]:
geoloc["geolocation_state"].nunique()

27

In [17]:
geoloc.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [18]:
geoloc["geolocation_lng"].describe()

count    1.000163e+06
mean    -4.639054e+01
std      4.269748e+00
min     -1.014668e+02
25%     -4.857317e+01
50%     -4.663788e+01
75%     -4.376771e+01
max      1.211054e+02
Name: geolocation_lng, dtype: float64

In [19]:
geoloc["geolocation_lat"].describe()

count    1.000163e+06
mean    -2.117615e+01
std      5.715866e+00
min     -3.660537e+01
25%     -2.360355e+01
50%     -2.291938e+01
75%     -1.997962e+01
max      4.506593e+01
Name: geolocation_lat, dtype: float64

In [20]:
geoloc = geoloc.drop_duplicates()

In [21]:
geoloc.duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
1000155    False
1000156    False
1000157    False
1000158    False
1000161    False
Length: 738332, dtype: bool

In [22]:
geoloc.shape

(738332, 5)

In [23]:
geoloc = geoloc[(geoloc['geolocation_lat'] >= -34) & (geoloc['geolocation_lat'] <= 5) & (geoloc['geolocation_lng'] >= -74) & (geoloc['geolocation_lng'] <= -32)]

In [24]:
geoloc.describe()

       geolocation_zip_code_prefix  geolocation_lat  geolocation_lng
count                738305.000000    738305.000000    738305.000000
mean                  38315.496510       -21.000067       -46.461944
std                   30632.552159         5.883399         4.382939
min                    1001.000000       -33.692616       -72.930746
25%                   12600.000000       -23.603070       -48.867804
50%                   29144.000000       -22.873621       -46.647296
75%                   65950.000000       -19.923395       -43.837205
max                   99990.000000         4.482242       -32.402779

In [25]:
print(geoloc['geolocation_lat'].min())
print(geoloc['geolocation_lat'].max())
print(geoloc['geolocation_lng'].min())
print(geoloc['geolocation_lng'].max())

-33.692616193040195
4.482241762160657
-72.93074575443762
-32.4027792713525

In [26]:
geoloc.to_csv(r"C:\Users\Administrator\Documents\1st Project\Processed_data\geolocation_clean.csv", index=False)

In [27]:
geoloc.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP