In [1]:
import pandas as pd

In [2]:
orderr = pd.read_csv(r"C:\Users\Administrator\Documents\1st Project\Raw_data\olist_order_reviews_dataset.csv")

In [3]:
orderr.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [4]:
orderr.columns

Index(['review_id', 'order_id', 'review_score', 'review_comment_title',
       'review_comment_message', 'review_creation_date',
       'review_answer_timestamp'],
      dtype='str')

In [5]:
orderr.shape

(99224, 7)

In [6]:
orderr.dtypes

review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

In [9]:
orderr.isnull().sum()

review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

In [11]:
orderr.duplicated().sum()

np.int64(0)

In [12]:
orderr["review_score"].unique()

array([4, 5, 1, 3, 2])

In [13]:
orderr["review_score"].describe()

count    99224.000000
mean         4.086421
std          1.347579
min          1.000000
25%          4.000000
50%          5.000000
75%          5.000000
max          5.000000
Name: review_score, dtype: float64

In [14]:
orderr["review_id"].duplicated().sum()

np.int64(814)

In [16]:
{col: orderr[col].duplicated().sum() for col in orderr.columns}

{'review_id': np.int64(814),
 'order_id': np.int64(551),
 'review_score': np.int64(99219),
 'review_comment_title': np.int64(94696),
 'review_comment_message': np.int64(63064),
 'review_creation_date': np.int64(98588),
 'review_answer_timestamp': np.int64(976)}

In [17]:
orderr["review_comment_title"] = orderr["review_comment_title"].fillna('')

In [18]:
orderr["review_comment_message"] = orderr["review_comment_message"].fillna('')

In [19]:
orderr.isnull().sum()

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [20]:
orderr["review_creation_date"] = pd.to_datetime(orderr["review_creation_date"])

In [21]:
orderr["review_answer_timestamp"] = pd.to_datetime(orderr["review_answer_timestamp"])

In [22]:
orderr.dtypes

review_id                             str
order_id                              str
review_score                        int64
review_comment_title                  str
review_comment_message                str
review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

In [23]:
orderr.insert(0, 'review_pk', range(1, len(orderr) + 1))

In [24]:
orderr.head()

,review_pk,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,1,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,,,2018-01-18,2018-01-18 21:46:59
1,2,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,,,2018-03-10,2018-03-11 03:05:13
2,3,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,,,2018-02-17,2018-02-18 14:36:24
3,4,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06
4,5,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53

In [25]:
orderr.dtypes

review_pk                           int64
review_id                             str
order_id                              str
review_score                        int64
review_comment_title                  str
review_comment_message                str
review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

In [28]:
orderr.to_csv(r'C:\Users\Administrator\Documents\1st Project\Processed_data\order_reviews_clean.csv', index = False)