In [1]:
import pandas as pd

In [2]:
prod = pd.read_csv(r"C:\Users\Administrator\Documents\1st Project\Raw_data\olist_products_dataset.csv")

In [3]:
prod.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [4]:
prod.shape

(32951, 9)

In [5]:
prod.columns

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')

In [6]:
prod.dtypes

product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [7]:
prod.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [8]:
prod.duplicated().sum()

np.int64(0)

In [9]:
prod['product_category_name'].nunique()

73

In [10]:
prod['product_category_name'].unique()

<StringArray>
[                                    'perfumaria',
                                          'artes',
                                  'esporte_lazer',
                                          'bebes',
                          'utilidades_domesticas',
                          'instrumentos_musicais',
                                     'cool_stuff',
                               'moveis_decoracao',
                               'eletrodomesticos',
                                     'brinquedos',
                                'cama_mesa_banho',
               'construcao_ferramentas_seguranca',
                         'informatica_acessorios',
                                   'beleza_saude',
                               'malas_acessorios',
                             'ferramentas_jardim',
                              'moveis_escritorio',
                                     'automotivo',
                                    'eletronicos',
                               'fashion_calcados',
                                      'telefonia',
                                      'papelaria',
                    'fashion_bolsas_e_acessorios',
                                            'pcs',
                                'casa_construcao',
                             'relogios_presentes',
              'construcao_ferramentas_construcao',
                                       'pet_shop',
                                'eletroportateis',
                      'agro_industria_e_comercio',
                                              nan,
                                    'moveis_sala',
                        'sinalizacao_e_seguranca',
                                   'climatizacao',
                                 'consoles_games',
                         'livros_interesse_geral',
             'construcao_ferramentas_ferramentas',
                 'fashion_underwear_e_moda_praia',
                        'fashion_roupa_masculina',
 'moveis_cozinha_area_de_servico_jantar_e_jardim',
                  'industria_comercio_e_negocios',
                                 'telefonia_fixa',
              'construcao_ferramentas_iluminacao',
                                'livros_tecnicos',
                             'eletrodomesticos_2',
                              'artigos_de_festas',
                                        'bebidas',
                                   'market_place',
                                     'la_cuisine',
                  'construcao_ferramentas_jardim',
                         'fashion_roupa_feminina',
                                  'casa_conforto',
                                          'audio',
                              'alimentos_bebidas',
                                         'musica',
                                      'alimentos',
                       'tablets_impressao_imagem',
                              'livros_importados',
                    'portateis_casa_forno_e_cafe',
                                'fashion_esporte',
                               'artigos_de_natal',
                  'fashion_roupa_infanto_juvenil',
                                   'dvds_blu_ray',
                             'artes_e_artesanato',
                                       'pc_gamer',
                                  'moveis_quarto',
                                      'cine_foto',
                                'fraldas_higiene',
                                         'flores',
                                'casa_conforto_2',
  'portateis_cozinha_e_preparadores_de_alimentos',
                             'seguros_e_servicos',
                      'moveis_colchao_e_estofado',
                              'cds_dvds_musicais']
Length: 74, dtype: str

In [14]:
prod[['product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']].describe()

,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32949.000000,32949.000000,32949.000000,32949.000000
mean,2276.472488,30.815078,16.937661,23.196728
std,4282.038731,16.914458,13.637554,12.079047
min,0.000000,7.000000,2.000000,6.000000
25%,300.000000,18.000000,8.000000,15.000000
50%,700.000000,25.000000,13.000000,20.000000
75%,1900.000000,38.000000,21.000000,30.000000
max,40425.000000,105.000000,105.000000,118.000000

In [15]:
(prod['product_weight_g'] == 0).sum()

np.int64(4)

In [16]:
prod[prod['product_weight_g'] == 0]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
9769,81781c0fed9fe1ad6e8c81fca1e1cb08,cama_mesa_banho,51.0,529.0,1.0,0.0,30.0,25.0,30.0
13683,8038040ee2a71048d4bdbbdc985b69ab,cama_mesa_banho,48.0,528.0,1.0,0.0,30.0,25.0,30.0
14997,36ba42dd187055e1fbe943b2d11430ca,cama_mesa_banho,53.0,528.0,1.0,0.0,30.0,25.0,30.0
32079,e673e90efa65a5409ff4196c038bb5af,cama_mesa_banho,53.0,528.0,1.0,0.0,30.0,25.0,30.0

In [21]:
category_median = prod[prod['product_category_name'] == 'cama_mesa_banho']['product_weight_g'].median()
print("Category median weight:", category_median)

prod['product_weight_g'] = prod['product_weight_g'].replace(0, category_median)

Category median weight: 1250.0

In [22]:
prod['product_weight_g'].describe()

count    32949.000000
mean      2276.624237
std       4281.980200
min          2.000000
25%        300.000000
50%        700.000000
75%       1900.000000
max      40425.000000
Name: product_weight_g, dtype: float64

In [28]:
prod['product_category_name'].isna().any()

np.True_

In [31]:
prod['product_id'].is_unique

True

In [32]:
prod.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [33]:
prod["product_category_name"] = prod['product_category_name'].fillna("unknown")

In [35]:
dim_cols = ['product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']
for col in dim_cols:
    prod[col] = prod[col].fillna(prod[col].median())

In [36]:
prod.isnull().sum()

product_id                      0
product_category_name           0
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                0
product_length_cm               0
product_height_cm               0
product_width_cm                0
dtype: int64

In [37]:
prod.dtypes

product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [38]:
prod.to_csv(r"C:\Users\Administrator\Documents\1st Project\Processed_data\products_clean.csv", index=False)